# Generated by Django 3.2.16 on 2023-03-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0002_auto_20230309_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watch_list.streamplatform'),
            preserve_default=False,
        ),
    ]
